### ISSUE TITLE
List of browser engine support?

### ISSUE THREAD

**Issue by jas-** [daviddahl/web-crypto-ideas#2]
I am running the latest chrome and Firefox for Linux and am wondering if the beta version implants the code in this repo of is it simply pseudo code? Any information is appreciated

**Comment by daviddahl** [comment]
no, this is pseudocode for the Web Cryptography Workng Group @ W3C. I do have an extension called DOMCrypt that provides a crypto API for Firefox.

**Comment by jas-** [comment]
I am familiar with the DOMCrypt Extension, great tool. I was hoping this was the case. As I was beginning to think I was going to have to get some alpha or beta builds setup just to test a plugin I have started to handle this once browser engines start making it available. Thanks for your time.
