### ISSUE TITLE
Storage interface

### ISSUE THREAD

**Issue by jas-** [daviddahl/web-crypto-ideas#3]
Sorry to bother you again, I have a question regarding the storage interface which is currently in the W3C spec (http://www.w3.org/2012/webcrypto/WebCryptoAPI/#examples-key-storage).

Your examples in this repo use the HTML5 localStorage mechanism. However the spec uses something else entirely. I am assuming the internals of this implementation will perform an AES and possibly combination of signing to store the generated key/key pair?

I ask because the plug-in I am getting prepped in anticipation for these features in the browser engines currently allows for multiple storage types (the default of course using the window.crypto.keys.getKeyById). The current interface will use developers choice of storage mechanism but I would like to ensure they will be protecting the keys and my assumption is that a combination of a signing & symmetric encryption will be used by the spec to do so.

Anyways, any light you can shed on the subject is appreciated.

**Comment by daviddahl** [comment]
The examples in this repo should always be public keys, the usage of localStorage was just for illustrating what a dev might do with a public key. The key storage spec is in flux, however, you can expect it to store keys by ID and the actual structure and type of key will vary. Some will be symmetric, some public keys. Private keys will probably be used by ID in a more opaque fashion.

**Comment by jas-** [comment]
I do something similar to this with another plug-in I wrote a awhile ago, implements a simple keyring with the browser.

In terms of the private keys, when you say 'opaque', are you referring to the storage & retrieval or the obfuscation, encryption/decryption & possibly signing of the private keys prior to storage?

I am also assuming the private keys would be stored using the sqlite functionality within the browser? This method leads me to believe that they (private keys) might be a bit further removed from the standard DOM storage mechanisms.

With this in mind, I am assuming the interface for retrieving them would simply require a developer to query for a public key, then using the return key; reference the private key (if needed) strictly using the window.crypto.keys.getKeyById() interface?

**Comment by daviddahl** [comment]
By "Opaque" I mean that any private key material will only ever be referenced by an ID - and its content will be used beyond the reach of the DOM.
Yes, (in the low level API) the private key material will not be accessible to the DOM unless you flag it as 'exportable' upon creation.
I think you might be right, getting a public key can then give you access to the corresponding private key ID.

Of course, all of this is still being devised. Feel free to study the spec and send comments: http://www.w3.org/TR/WebCryptoAPI/

**Comment by jas-** [comment]
I think the note about exporting helps me understand how this will be accessible, if at all by the DOM. Thanks for your time Mr. Dahl

**Comment by daviddahl** [comment]
Anytime.
