### ISSUE TITLE
Diffie hellman

### ISSUE THREAD

**Issue by jas-** [daviddahl/web-crypto-ideas#4]
I feel like I am really hounding you at this point. However reviewing the spec further I see native Diffie Hellman support is in the works as well. My assumption is the native PRNG (also planned under this spec) will be used for the prime number generation. Either under a low level, or high level API are you aware of a native prime only number generator planned for use with the Diffie-Hellman functionality?

**Comment by daviddahl** [comment]
The PRNG is window.crypto.getRandomValues() - currently available in Chrome and someday soon in Firefox

**Comment by jas-** [comment]
Maybe I my question was too vague. The window.crypt.getRandomValues() function is what I was referring to, however I was asking if it would generate only primes in terms of diffie-hellman key exchange use?

**Comment by daviddahl** [comment]
Ah, indeed. So, I imagine there will be specific functions for each step involved with DH exchange. getRandomValues is very generic, just handing you back random data of any length you specify in the typedArray passed in. I don't expect it to be changed for future DH functionality.

**Comment by daviddahl** [comment]
Also, this is all very hand-wavy right now:)

**Comment by jas-** [comment]
Yeah I am aware of the lack of current support in most engines, just trying to ensure that when they are present the project I am working on can use the functionality in the proper way.

**Comment by jas-** [comment]
Hello again Mr. Dahl,

Do you ever review others code? I am in the process of creating a 'wrapper' for web developers that wish to implement the crypto API in a safe way and would like someone with a bit more knowledge on the subject to sign off on its current implementation. Of course none of the browsers I have found currently support any (even nightly builds) specs API. In any event the project is at https://github.com/jas-/crypto.js. I have taken great care in documenting everything to make it very simple to extend. Thanks again.

**Comment by daviddahl** [comment]
I will attempt to do so, however, I am not a crypto expert by any stretch of the imagination. Alos, ping me again in a few weeks if you have heard nothing.

Cheers.

**Comment by jas-** [comment]
Ping. According to the w3c draft regarding the crypto api it seems that participation may come as a benefit in regards to keeping abreast of api changes etc.

I have taken steps to create an account at w3.org but need an invite to the crypto api group? Forgive me if I missed a step but I would very much like to ensure that the project listed above (https://github.com/jas-/crypto.js) adheres to the specifications put forth by this charter. Thanks.

**Comment by daviddahl** [comment]
You should join the mailing list: http://lists.w3.org/Archives/Public/public-webcrypto/

You should introduce yourself and send along a link to your github, if you work for a company that has w3 membership, you can easily get into the WG, if not, we may be able to invite you as an "invited expert".

**Comment by daviddahl** [comment]
Also, I am working on a more formal draft of my high-level API here: https://dvcs.w3.org/hg/webcrypto-highlevel/raw-file/30d26e80c3e9/Overview.html

**Comment by jas-** [comment]
I looked at the list of current companies and did not see my employer (University Of Utah) on the list originally during sign up.

The high level API seems to be used for the Polycrypt project as well. Thank you for the information, I will be posted something soon.

**Comment by hhalpin** [comment]
On 01/23/2013 05:12 PM, Jas- wrote:

> I looked at the list of current companies and did not see my employer 
> (University Of Utah) on the list originally during sign up.
> 
> The high level API seems to be used for the Polycrypt project as well. 
> Thank you for the information, I will be posted something soon.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/daviddahl/web-crypto-ideas/issues/4#issuecomment-12602792. 
> 
> Universities generally can be added as Invited Experts without a huge 
> problem.

Do you plan to actively participate in phone calls/figuring out issues?

```
cheers,
 harry
```

**Comment by jas-** [comment]
Currently I foresee my involvement as being limited in scope. I am working on the project mentioned above to implement this API in as secure a method as possible while including a few features such as choices of storage mechanisms, logging levels etc. (Currently supports cookies, localStorage, sessionStorage, remote storage by way of PHP proxy w/ MySQL backend)

Of course it is up in the air as there is no current support in any browser for this API as of yet but by following the various discussions, use cases & test cases I plan on adhering to the recommendations of the group as I am not a crypto expert.

I just would like to provide the community with a simple to use interface while ensuring best practices are being followed.

**Comment by jas-** [comment]
Hello again. I have been following the mailing list discussions @ public-webcrypto@w3.org and have a question regarding existing PKI elements in (most) browsers.

My specific question is in regards to the `<keygen>` element specified in [the W3C HTML5 draft](http://dev.w3.org/html5/markup/keygen.html).

Will the private key generated with this element be available for assisting with decryption of server (or client(s) via the WebRTC channel(s)) data encrypted using the exported public key from the SPKAC?

I would have asked this on the mailing list but am not allowed. Thanks!

**Comment by daviddahl** [comment]
I think if Mozilla could get rid of <keygen> we would. It is very cumbersome and not in widespread use. I don't think there will be any use of it in Web Crypto API WG, I do not know about WebRTC, but I doubt it.

**Comment by jas-** [comment]
Strange that it should be included in the latest draft (as well as those in the HTML4 draft(s)) but not considered in the latest crypto api for using existing certificates/keys created by the element.

So with that in mind I am assuming a complete rewrite of the private keystore is to be anticipated?
